language: dart

dart:
  - stable
  - dev

branches:
  only: [master]

dart_task:
  - test: --exclude-tags "ipv6"

script:
  - cd packages/universal_io
  - pub get
  - pub run test
  - cd ../..
  - cd packages/test_io
  - pub get
  - pub run test
  - cd ../..
  - cd packages/chrome_os_io
  - pub get
  - pub run test
  - cd ../..
  - cd samples/chrome_app_example
  - pub get
  - pub run webdev build