name: universal_io
version: 2.0.0-nullsafety.2
description: Cross-platform 'dart:io' that works in all platforms (browsers, Flutter, and VM).
homepage: https://github.com/dart-io-packages/universal_io

environment:
  sdk: '>=2.12.0-133.2 <3.0.0'

dependencies:
  collection: ^1.15.0-nullsafety.4
  crypto: ^3.0.0-nullsafety.0
  meta: ^1.3.0-nullsafety.6
  typed_data: ^1.3.0-nullsafety.5

dev_dependencies:
  pedantic: ^1.10.0-nullsafety.3
  test: ^1.16.0-nullsafety.13

dependency_overrides:
  crypto: ^3.0.0-nullsafety.0