name: universal_io
version: 2.0.0
description: Cross-platform 'dart:io' that works in all platforms (browsers, Flutter, and VM).
homepage: https://github.com/dart-io-packages/universal_io

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  crypto: ^3.0.0
  meta: ^1.3.0
  typed_data: ^1.3.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.0