name: universal_io
version: 0.8.4
description:
  Cross-platform 'dart:io' that works in browsers, Flutter, and VM.
homepage: https://github.com/terrier989/universal_io
author: terrier989 <terrier989@gmail.com>

environment:
  # This package is not actually 2.4.x compatible!
  #
  # Unfortunately, if we use 2.5.0-dev-2.1, pub.dev/packages/universal_io would show big red
  # warnings to potential users of this package.
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  meta: ^1.1.0
  zone_local: '>=0.1.1 <2.0.0'

dev_dependencies:
  async: ^2.3.0
  pedantic: ^1.8.0
  stream_channel: ^2.0.0
  test: ^1.6.0