name: universal_io
version: 0.7.3
description:
  Cross-platform 'dart:io' that works in VM/Flutter, browsers, and elsewhere.
homepage: https://github.com/terrier989/dart-universal_io
author: terrier989 <terrier989@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  meta: ^1.1.7
  zone_local: '>=0.1.0 <2.0.0'

dev_dependencies:
  async: ^2.2.0
  pedantic: ^1.7.0
  stream_channel: ^2.0.0
  test: ^1.6.3