name: universal_io
version: 0.4.0
description:
  Cross-platform version of 'dart:io'. Supports browsers, Node.JS, and other targets.
homepage: https://github.com/gohilla/dart-universal_io
author: terrier989 <terrier989@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  ip: ^0.1.1
  meta: ^1.1.7
  zone_local: ^0.1.0

dev_dependencies:
  pedantic: ^1.7.0
  stream_channel: any
  test: ^1.6.3