name: nodejs_io
version: 0.1.0
description: Enables use of 'dart:io' APIs in Node.JS.
homepage: https://github.com/dart-io-packages/universal_io

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  meta: ^1.1.7
  node_io: ^1.0.0
  node_http: ^1.0.0
  universal_io: ^0.8.5

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.8.0