name: universal_io
version: 1.0.2
description: Cross-platform 'dart:io' that works in all platforms (browsers, Flutter, and VM).
homepage: https://github.com/dart-io-packages/universal_io

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  crypto: ^2.1.5
  meta: ^1.1.0
  zone_local: '>=0.1.0 <=0.3.0'

dev_dependencies:
  async: ^2.4.0
  pedantic: ^1.9.0
  stream_channel: ^2.0.0
  test: ^1.8.0