name: universal_io
version: 0.9.0
description: Cross-platform 'dart:io' that works in browsers, Flutter, and VM.
homepage: https://github.com/dart-io-packages/universal_io

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  meta: ^1.1.0
  zone_local: '>=0.1.1 <2.0.0'

dev_dependencies:
  async: ^2.4.0
  pedantic: ^1.9.0
  stream_channel: ^2.0.0
  test: ^1.8.0