name: chrome_app_example
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  chrome_os_io:
    path: '../../packages/chrome_os_io'
  universal_io:
    path: '../../packages/universal_io'

dev_dependencies:
  build_runner: any
  build_web_compilers: any
  webdev: any

dependency_overrides:
  universal_io:
    path: '../../packages/universal_io'
