name: test_io
version: 0.1.0
description: Access to environmental variables in browsers ando other helpers for testing.
homepage: https://github.com/dart-io-packages/universal_io/test_io

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  meta: ^1.1.0
  stream_channel: ^2.0.0
  test: ^1.8.0

dev_dependencies:
  pedantic: ^1.9.0