name: chrome_app_example
version: 0.0.1

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  universal_io:
    path: '../..'

dev_dependencies:
  build_runner: '>=0.8.10 <2.0.0'
  build_web_compilers: '>=0.3.6 <2.0.0'
  webdev: ^1.0.1