name: chrome_io
version: 0.1.0
description: Enables use of 'dart:io' in Chrome OS Apps (TCP/UDP sockets, etc.).
homepage: https://github.com/terrier989/chrome_io
author: terrier989 <terrier989@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  meta: '^1.1.7'
  universal_io: '^0.8.4'

dev_dependencies:
  pedantic: '^1.0.0'
  test: '^1.4.0'
  webextdev: ^0.1.3