name: chrome_io
version: 0.1.0
description: Enables use of 'dart:io' in Chrome OS Apps (TCP/UDP sockets, etc.).
homepage: https://github.com/terrier989/universal_io

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  meta: '^1.1.7'
  universal_io: '^0.8.5'

dev_dependencies:
  pedantic: '^1.9.0'
  test: '^1.8.0'
  webextdev: '^0.1.3'